### ISSUE TITLE
Remove Core's dependency on Linq

### ISSUE THREAD

**Issue by tomrijnbeek** [beardgame/utilities#108]
The `Core` and `Linq` namespaces form a dependency cycle. In my opinion `Core` should not depend on anything and stand on its own, so we should move the code that depends on `Linq` somewhere else.

![image](https://user-images.githubusercontent.com/828553/28740191-ea170cd2-73f9-11e7-9836-d5a684c3b5ff.png)

In particular, this is the `IdManager` using the `ValueOrDefault` extension.

![image](https://user-images.githubusercontent.com/828553/28740218-33c3d77a-73fa-11e7-9edb-b345a5f4ee7a.png)

**Comment by amulware** [comment]
Sure. How come Core relies on Math? That seems strange.

**Comment by tomrijnbeek** [comment]
It seems like Logger relies on Math for some reason. A quick check shows we use the `.Clamped` extension. We can probably just replace that with a `System.Math.Clamp`.

**Comment by amulware** [comment]
System.Math.Clamp is a thing? Huh.

**Comment by tomrijnbeek** [comment]
Oh no, it's not :(
