### ISSUE TITLE
Fix stylecop analysis

### ISSUE THREAD

**Issue by tomrijnbeek** [beardgame/utilities#148]
We have the StyleCop Roslyn analyzer enabled, but looking at the build logs, there are a lot of errors since we never actually put all the rules in the StyleCop config:

![](https://i.gyazo.com/b804ec4f497ed4d1c7fb977df2947887.png)

We should either remove the StyleCop analyzer, or update the config. I don't think StyleCop adds a lot of value, so I personally suggest removing the analyzer altogether, since that appears to be the easiest solution.

**Comment by amulware** [comment]
I agree that it doesn't add a lot of value given the lower number of contributors and our relatively low development velocity.

Let's 🔥 it for now.
