### ISSUE TITLE
[Proposal] Stop releasing NuGet versions at HEAD automatically

### ISSUE THREAD

**Issue by tomrijnbeek** [beardgame/utilities#174]
I wonder if we should stop releasing new versions to NuGet on every PR. While it makes it easy to quickly integrate changes to the Utilities in other projects this way, I don't think it is clear what version to use outside of the authors. In many cases, there is no reason to restrict releasing the new changes to only a pre-release version. As long as they are additions, rolling out a new minor version should be relatively straightforward if we commit to the process changes (see #173). This would also provide an actively developed library more publicly. We can still release pre-release versions as well, but these would have to be manually tagged.

If projects really need the latest and greatest, they can always submodule this repository, but in my opinion there doesn't have to be anything wrong with actually releasing the changes when needed as an actual version.

**Comment by amulware** [comment]
I already don't always put new utilities in here because of the added effort and delay with waiting for the package.

It seems to me like removing automatic builds would make this hurdle even bigger.

**Comment by tomrijnbeek** [comment]
Just to be clear, I'm not suggesting to remove automatic builds altogether.
The only change that I'm suggesting is that the created builds are not
automatically uploaded to NuGet. Instead, they are only pushed when a tag
is attached to a commit.

In general, if we want to take versioning a bit more seriously (see #173),
we'd have to make the release script a bit smarter anyway most likely, so
it makes sense to link that to tags.

Regarding it increasing the hurdle to add new utility classes. I wonder how
much the build and release cycle actually adds to that friction compared to
having to send a PR for review. Adding only a step to push a tag seems
fairly negligible to me.

**Comment by amulware** [comment]
I see your point that pushing a tag. Though, we won't actually review releases in any way then? Don't we need to change the changelog or a version number somewhere?

**Comment by tomrijnbeek** [comment]
Version codes are already automatically patched in. Something we will have
to patch in ourselves potentially is the changelog, and I'm thinking we can
then have the CI automatically commit an updated changelog with the version
number added and all the changes, but I'm not sure how easy that would be.

We could always forego this for prerelease versions, but I'd like to get to
a better cadence of actual release versions so investing in a pipeline for
that seems worth it.

**Comment by tomrijnbeek** [comment]
This is now done.
