### ISSUE TITLE
Interpolation out of [0, 1] range treatment

### ISSUE THREAD

**Issue by amulware** [beardgame/utilities#29]
While looking through the Interpolation class (see issue #8), I noticed that most but not all interpolating methods clamp the interpolating parameter to the range of [0, 1].

Is there a reason that some do not do so?

**Comment by tomrijnbeek** [comment]
By my knowledge this is only the case for the BiLerp methods which you originally wrote. In the private methods the lack of clamping is intentional.

**Comment by amulware** [comment]
I think that all methods in that class should have the same behaviour.

Should we make all of them clamp to [0, 1] then?

Otherwise, we could leave that up to the user, or provide Interpolation.Clamped methods.

**Comment by tomrijnbeek** [comment]
I have no problem clamping the BiLerp method to [0, 1]. I think you might have made an intentional choice with not clamping them originally, because it is even mentioned in the comments.

**Comment by amulware** [comment]
I added the clamping in #31, what I wonder though is what is up with the Hermite method. It also does not seem to have clamping, but treads the two equals cases especially.

Should I add clamping to this as well? Or does it not have clamping on purpose?
In either case, the method can be slightly optimised, which I would do in either case.

A related issue:

The comments in the Hermite method mention that values are cast to double to prevent NaN and Infinity. However, there does not seem to be any dangerous math (like divisions or powers).
Am I missing something?

**Comment by tomrijnbeek** [comment]
The method comes directly from MonoGame, so I am afraid I can not comment on these issues adequately.

**Comment by amulware** [comment]
Going to improve Hermite interpolation method similar to others.
