### ISSUE TITLE
Use different test framework.

### ISSUE THREAD

**Issue by tomrijnbeek** [beardgame/utilities#33]
While the current testing framework (MStest) is very convenient, it is only supported in Visual Studio. Hence the tests only work on Windows. While the library should be completely usable through Mono, we would have to switch to either [xUnit](https://github.com/xunit/xunit) or [NUnit](https://github.com/nunit/nunit) to make the library wholly usable among all platforms.

I personally think xUnit would be the better choice, as it seems to allow for integration with Visual Studio in a similar manner as MSBuild.

**Comment by amulware** [comment]
I have no issues with this. Feel free to go ahead and set things up as required.
