### ISSUE TITLE
Add game components framework

### ISSUE THREAD

**Issue by tomrijnbeek** [beardgame/utilities#40]
I am currently working on a framework to support component-based game object management, which I will further expand on in some blog posts. The main features will be a very basic framework that manages components and inter-component communication.

It might be interesting to add this to this library as well. Not everybody will be wanting to use that, but we have several components (no pun intended) that are already optional to use. The current repository is mainly set up as a very generic thing to act as example, so we probably have to make some decisions about what exactly we will want to include if we were to add this to the utilities library.

Current repository: https://github.com/tomrijnbeek/game-components

**Comment by amulware** [comment]
Sounds interesting to me.

I'll look into that sometime, and we can discuss how to best handle it then.

**Comment by tomrijnbeek** [comment]
What is your opinion in duplicating the interface to the `ComponentCollection` methods into the `Component` abstract class. That is, there would be methods for `AddComponent`, `GetComponent`, `RemoveComponent`, and `SendMessage` on the `Component` as well, allowing for e.g. a `this.GetComponent` call instead of `this.collection.GetComponent`, which would allow us to even completely hide the `this.collection` reference from subclasses.

**Comment by amulware** [comment]
I am concerned that it is not completely clear that the methods search for/add _sibling_ components. Also not sure if it necessarily. Is there an advantage of hiding the component member?

**Comment by tomrijnbeek** [comment]
Right now its development is on hold, and the implementation we do have is part of the beardgame/game repository. So for now I'll close this issue. We can see if we want to move this into here if we ever continue developing it.
