### ISSUE TITLE
GameMath -> Mathf

### ISSUE THREAD

**Issue by tomrijnbeek** [beardgame/utilities#41]
After working with Unity a bit more, I would suggest renaming the `GameMath` class to `Mathf`, or possibly even separating the basic math functions (`Cos`, `Sqrt`, etc.) into a `Mathf` class since they provide the same basic functionality as `Math` but on floats. This also saves a few characters in writing them in case that is important. Whether to include more "complicated" functions in `Mathf` or keep them in a separate `GameMath` class is open to discussion.

**Comment by amulware** [comment]
I can see the sense in that. While I like long and descriptive names, there is really no reason why it should be `GameMath`, instead of `SomethingElseMath`.

I am divided on where to put the functionality that is not just a float version of something in `Math`.
