### ISSUE TITLE
IntVector(2)

### ISSUE THREAD

**Issue by tomrijnbeek** [beardgame/utilities#42]
I think having an IntVector2 class would be helpful. It is something I am really missing now I am working on a grid-based game in Unity. Moreover, I think we should try to work out if we can make an extension method in such a way that allows retrieval from two-dimensional arrays by IntVector2. That is:

```
var intArray = new int[3,14];
var coordinates = new IntVector2(1,12);
return intArray.At(coordinates); // returns int[1,12]
```

**Comment by amulware** [comment]
```public static

**Comment by amulware** [comment]
```
public static T At<T>(this T[,] array, IntVector2 xy)
{
    return array[xy.X, xy.Y];
}
```

Assuming this compiles.

Overall, this sounds fine to me. Though, I would argue that using a type that is not merely an IntVector, but actually _a position in a 2d grid_, coupled with an appropriate generic tilemap type may be nicer. Definitely something to discuss.

**Comment by amulware** [comment]
On hold.
