### ISSUE TITLE
Mathf.(Ceil|Floor|Round)ToInt takes doubles

### ISSUE THREAD

**Issue by amulware** [beardgame/utilities#58]
The class is called Math**f**. Should it have methods with doubles in their signature?

**Comment by tomrijnbeek** [comment]
I think the class's main intention is to provide a basic toolset that works with both integers and floats. This method would help with turning a double (for example from a System class) into an integer.

I don't know, I don't think it's a big deal.

**Comment by amulware** [comment]
Given that the `System.Math` methods called use double anyways this also would not include any unneeded casts/conversions.
