### ISSUE TITLE
Useful additions to SpaceTime

### ISSUE THREAD

**Issue by amulware** [beardgame/utilities#63]
While working with the SpaceTime types, I found a few things missing that would have been nice to have:
- dot product (between vector types)
- cross product (same)
- unit \* unit -> sqr<unit> and similar
- add more operators to sqr<> to allow it to be used just like unit, etc.
  - this may be a bad idea with the current idea of ensuring positivity of the value, but it might come in handy when used to represent area for example

**Comment by amulware** [comment]
A key point here is whether negative values should be allowed for Squared<>, or if we should add a second type for it or neither.

I remember having the same discussion about the other one dimensional types like Unit, Speed, etc.
Those currently allow negative values, even though arguably that makes no sense.

I am divided.

**Comment by tomrijnbeek** [comment]
I like the additions, though I think we would have to check all the use cases to make sure they make sense. I.e. does taking the dot product between an acceleration and a difference ever make sense?

In terms of using squares for area, shouldn't that be a typesafe `Area` type? In that case `unit * unit` can become more than one thing. In my mind a `Square` is a very specific type of product (namely that of a unit with itself). I am not implying we need the `Area` right now, but I am also not sure if we should lock ourself into making `unit * unit -> sqr`.

Regarding negative values: we may have to really think about all the use cases of one-dimensional types. I would be okay enforcing negative values, but there is one other thing we should consider (and have in the past): this means an extra check every time we construct a SpaceTime object. This while SpaceTime object creation can potentially happen in performance-critical parts of game code. We could always have the precondition checks run as debug-only, but that gives no guarantees in release binaries, so I am not sure what we get from that.

**Comment by amulware** [comment]
Good points. I might be ok with including `Area` then. And maybe have a conversion from `Square` to `Area`.

About extra checks: No. If we have types which don't allow negatives, then we don't allow operations that could get us there. For example, there is a `Square+Square` operator, but no `Square-Square`.

**Comment by tomrijnbeek** [comment]
I think that makes sense, though that doesn't prevent initialising instances manually using `new Squared(-1)`.

**Comment by amulware** [comment]
That is true, and that will indeed fail (though that specific constructor is internal and skips the check, because we can trust our own code, duh).

**Comment by amulware** [comment]
The current implementation seems to be reasonably complete and cover most cases. More behaviour should be implemented when the need arises during actual usage.
