### ISSUE TITLE
Add remaining XML comments

### ISSUE THREAD

**Issue by tomrijnbeek** [beardgame/utilities#79]
Right now we get a whole bunch of warnings about missing XML comments. We could add them, but the question is if we want to commit to commenting all public-facing interfaces. It also does add a lot of clutter to the code in a way, and I am always divided by what the right choice is.

So either way, let's decide between:

* Fixing all the warnings by adding XML comments.
* Removing the warnings altogether, but decide on a different documentation standard.

**Comment by amulware** [comment]
I think we should remove them. The project is open source, and mostly self explanatory. We can still leave comments on the more complicated things (like fancy algorithms) to explain some of the nuances.
